# -*- coding: utf-8 -*-
"""homework_2_1_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cE-odV1ws2gHZQrEHC44OK7MRQqYobIq
"""

def debug_control(*elements):
    element = 0
    for i in elements:
        element += 1
    return element
debug_control("Hello!", 1000, 7)