# -*- coding: utf-8 -*-
"""homework_2_1_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cE-odV1ws2gHZQrEHC44OK7MRQqYobIq
"""

def debug_control(*elem1, **elem2):
    int_, str_, float_= 0, 0, 0
    for i in elem1:
        if type (i) is str:
            str_ += 1
        elif type (i) is int:
            int_ += 1
        elif type (i) is float:
            float_ += 1
    for i in elem2:
        if type (i) is str:
            str_ += 1
        elif type (i) is int:
            int_ += 1
        elif type (i) is float:
            float_ += 1
    print("Str:", str_, "Int:", int_, "Float:", float_)
debug_control("Hello!", 1000, 7, 993.0, name="Petr", task="Eliminate")