# -*- coding: utf-8 -*-
"""homework_2_1_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cE-odV1ws2gHZQrEHC44OK7MRQqYobIq
"""

def greetings(a):
  g = "Доброго времени суток, " + a[0] + ' "Человек" ' + a[1] + "!"
  return g
greetings(input().split())