# -*- coding: utf-8 -*-
"""homework_2_1_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cE-odV1ws2gHZQrEHC44OK7MRQqYobIq
"""

a = input().split()
a1, b = [], []
def summation(a):
    for i in a:
        i = int(i)
        if i < 0:
            a1.append(i * -2)
        else:
            a1.append(i)
    mx = max(a1)
    for i in a1:
        b.append(i/mx)
    sm = sum(b)
    print(sm)
summation(a)