# -*- coding: utf-8 -*-
"""homework_1_2_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AfM2JJ7VCX5E06DyBNbIaHcESTGB7Ley
"""

numbers = int(input())
offline = 0
online = 0
for x in range(numbers):
  user = input().split()
  if 'True' in user:
    offline += 1
  if 'False' in user:
    online += 1
print(offline, online)