# -*- coding: utf-8 -*-
"""homework_1_1_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AfM2JJ7VCX5E06DyBNbIaHcESTGB7Ley
"""

numbers = input().split()
int_lst = [int(x) for x in numbers]
min = 1
max = 1
for x in int_lst:
    if min > x:
        min = x
    if max < x:
        max = x
print(min)
print(max)