# -*- coding: utf-8 -*-
"""homework_1_1_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AfM2JJ7VCX5E06DyBNbIaHcESTGB7Ley
"""

a = input().split()
print(a[::-1])