# -*- coding: utf-8 -*-
"""homework_1_1_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AfM2JJ7VCX5E06DyBNbIaHcESTGB7Ley
"""

str = input()
n = 1
numbers = [str[i:i+n] for i in range(0, len(str), n)]
if len(numbers) < 5:
  numbers.reverse()
  print(numbers[0:5:2])
else:
  print(numbers[3:6:2])