# -*- coding: utf-8 -*-
"""homework_1_2_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AfM2JJ7VCX5E06DyBNbIaHcESTGB7Ley
"""

shifr = input()
n = 1
symbols = [shifr[i:i+n] for i in range(0, len(shifr), n)]
for word in symbols:
  if word.isupper():
    index1st = symbols.index(word)
    break
for number in symbols:
  if number.isdigit():
    index2nd = symbols.index(number)
    break
shag = index2nd - index1st + 1
slovo = symbols[index1st::shag]
slovo = [''.join(slovo)]
print(slovo[0])